name: ci-build-push-ghcr-by-date

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate date tag
        id: date
        run: echo "tag=$(date +%Y%m%d-%H%M)" >> "$GITHUB_OUTPUT"

      - name: Lowercase repository info
        id: repo_info
        run: |
          echo "owner_lower=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          echo "repo_lower=$(echo "${{ github.event.repository.name }}" | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ steps.repo_info.outputs.owner_lower }}/${{ steps.repo_info.outputs.repo_lower }}
          tags: |
            type=raw,value=${{ steps.date.outputs.tag }}
            type=raw,value=latest

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug info
        run: |
          echo "Repository owner: ${{ github.repository_owner }}"
          echo "Repository name: ${{ github.event.repository.name }}"
          echo "Lowercase owner: ${{ steps.repo_info.outputs.owner_lower }}"
          echo "Lowercase repo: ${{ steps.repo_info.outputs.repo_lower }}"
          echo "Image tags: ${{ steps.meta.outputs.tags }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          provenance: false
