name: ci-build-push-ghcr-by-date

on:
  push:
    branches:
      - main          # 仅跟踪 main 分支，可改成 master 或 dev

env:
  IMAGE_NAME: ${{ github.repository }}   # owner/repo

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1. 生成“日期+时间”标签，如 20251003-1532
      - name: Generate date tag
        id: date
        run: echo "tag=$(date +%Y%m%d-%H%M)" >> "$GITHUB_OUTPUT"

      # 2. 同时生成 latest 标签
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.date.outputs.tag }}
            type=raw,value=latest

      # 3. 登录 ghcr.io
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 4. 多架构
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      # 5. 构建并推送（含详细日志）
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
